FROM node

ARG CLIENT_URL
ARG SERVER_URL
ARG STRIPE_PUBLIC_KEY
ARG BILLING_ENABLED
ARG DISABLE_PAYMENT

ENV PL_CLIENT_URL $CLIENT_URL
ENV PL_SERVER_URL $SERVER_URL
ENV PL_BILLING_ENABLED $BILLING_ENABLED
ENV PL_BILLING_DISABLE_PAYMENT $DISABLE_PAYMENT
ENV PL_BILLING_STRIPE_PUBLIC_KEY $STRIPE_PUBLIC_KEY

ENV PL_SERVER_PORT=3000
ENV PL_CLIENT_PORT=8080
ENV PL_DB_PATH=/data
ENV PL_ATTACHMENTS_PATH=/docs

EXPOSE 3000
EXPOSE 8080

VOLUME ["/app", "/data", "/docs"]

WORKDIR /padloc

COPY . .

RUN npm ci --unsafe-perm
RUN npm run build

CMD ["npm", "start"]
