name: Update Dockerhub

on:
    workflow_dispatch:

    push:
        branches:
            - "main"
        paths:
            - "packages/app/**"
            - "packages/core/**"
            - "packages/locale/**"
            - "assets/**"

jobs:
    update_dockerhub:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image (server)
              uses: docker/build-push-action@v3
              with:
                  push: true
                  tags: padloc/server:latest
                  file: Dockerfile-server

            - name: Build and push Docker image (pwa)
              uses: docker/build-push-action@v3
              with:
                  push: true
                  tags: padloc/pwa:latest
                  file: Dockerfile-pwa
