name: Update Deployments

on:
    workflow_dispatch:

    push:
        branches:
            - "main"
        paths:
            - "packages/app/**"
            - "packages/core/**"
            - "packages/locale/**"
            - "assets/**"

jobs:
    trigger-gh-action:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                instance: ["test", "beta"]
        env:
            DEPLOY_INSTANCE: ${{ matrix.instance }}
            DEVOPS_GITHUB_REPO: ${{ secrets.DEVOPS_GITHUB_REPO }}
        steps:
            - name: Trigger GH Action
              if: ${{ env.DEVOPS_GITHUB_REPO }}
              run: |
                  curl --request POST \
                    --url https://api.github.com/repos/${{ env.DEVOPS_GITHUB_REPO }}/actions/workflows/update-deployment.yml/dispatches \
                    --header 'Authorization: Basic ${{ secrets.DEVOPS_BASIC_AUTH_TOKEN }}' \
                    --header 'Content-Type: application/json' \
                    --data '{
                        "ref": "main",
                        "inputs": {
                            "instance": "${{ env.DEPLOY_INSTANCE }}",
                            "branch": "${{ github.sha }}"
                        }
                    }'
